from django.urls import path
from AppCoder import views

urlpatterns = [
    path('', views.inicio,name='Inicio'),
    path('cursosApi/', views.cursosapi),
    path('profesoresApi/', views.profesoresapi),
    path('cursos/', views.cursos, name='Cursos'),
    path('profesores/', views.profesores, name='Profesores'),
    path('egresados/', views.egresados, name='Egresados'),
    path('busquedaCurso/', views.buscarcurso, name='BuscarCurso'),
    path('busquedaProfesor/', views.buscarprofesor,name='BuscarProfe'),
    path('buscar/', views.buscar),
    path('buscarprofe/',views.buscarprofe),
    path('busquedaEgresado/', views.buscaregresado, name='BuscarEgreso'),
    path('buscaregreso/', views.buscaregreso),
    path('leercurso/', views.leer_curso),
    path('crearcurso/', views.crear_curso),
    path('editarcurso/', views.editar_curso),
    path('eliminarcurso/', views.eliminar_curso),
    path('curso/create/', views.CursoCreate.as_view(),name='New'),
    path('curso/list/', views.CursoList.as_view(),name='List'),
    path('curso/edit/<pk>', views.CursoEdit.as_view(),name='Edit'),
    path('curso/detail/<pk>', views.CursoDetail.as_view(),name='Detail'),
    path('curso/delete/<pk>', views.CursoDelete.as_view(),name='Delete'),
    path('profesores/list/', views.ProfeList.as_view(),name='ListProfe'),
    path('profesores/detail/<pk>', views.ProfeDetail.as_view(),name='DetailProfe'),
    path('profesores/edit/<pk>', views.ProfeEdit.as_view(),name='EditProfe'),
    path('profesores/delete/<pk>', views.ProfeDelete.as_view(),name='DeleteProfe'),
    path('profesores/create/', views.ProfeCreate.as_view(),name='NewProfe'),
    path('egresados/create/', views.EgresoCreate.as_view(),name='NewEgreso'),
    path('egresados/list/', views.EgresoList.as_view(),name='ListEgreso'),
    path('egresados/detail/<pk>', views.EgresoDetail.as_view(),name='DetailEgreso'),
    path('egresados/edit/<pk>', views.EgresoEdit.as_view(),name='EditEgreso'),
    path('egresados/delete/<pk>', views.EgresoDelete.as_view(),name='DeleteEgreso'),
]