# Generated by Django 4.1.3 on 2022-12-13 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_rename_egresado_egresados_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresados',
            name='graduacion',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='egresados',
            name='promedio',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesores',
            name='actividad',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesores',
            name='cargo',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
