# Generated by Django 4.1.3 on 2022-12-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0006_egresados_graduacion_egresados_promedio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='costo',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='duracion',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
