# Generated by Django 4.1.3 on 2022-12-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0007_curso_costo_curso_duracion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='camada',
            new_name='inicio',
        ),
        migrations.AlterField(
            model_name='profesores',
            name='cargo',
            field=models.CharField(max_length=40),
        ),
    ]
